### ISSUE TITLE
Tailwind css not working !!!

### ISSUE THREAD

**Issue by Said1996** [chrissainty/BlazorTailwindNDCOslo2021#1]
I have downloaded this code, built it and tailwind doesn't work for the classes I add (it works for your classes only).
Is there some hidden files or commands that I need to run before running this code?

**Comment by chrissainty** [comment]
It sounds like you're not running the Tailwind CLI. If you're not running it the JIT compiler won't be active and no new classes will be picked up.

**Comment by Said1996** [comment]
Excuse my french, but I have downloaded the standalone tailwind-cli for windows tried to install but its not working, Is that what you meant by not running Tailwind CLI?
